app_form4validacionregistro:
    resource: "@AppBundle/Resources/config/routing/form4validacionregistro.yml"
    prefix:   /form4validacionregistro

app_admmaster:
    resource: "@AppBundle/Resources/config/routing/admmaster.yml"
    prefix:   /admmaster